version: "3.9"

services:
  app:
    build: .
    command: ["python", "-m", "app.cli", "api"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/classroom
  pipeline:
    build: .
    command: ["python", "-m", "app.cli", "pipeline"]
    volumes:
      - .:/app
    depends_on:
      - rabbitmq
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/classroom
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classroom
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
